default:
    path:     /
    defaults: { _controller:  AppBundle:Services:index }

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

appbelge:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
